USE [master]
GO

/****** Object:  Database [WebHelpDesk]    Script Date: 02/19/2014 13:15:48 ******/
CREATE DATABASE [WebHelpDesk] ON  PRIMARY 
( NAME = N'WebHelpDesk', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\WebHelpDesk.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WebHelpDesk_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\WebHelpDesk_log.ldf' , SIZE = 6272KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WebHelpDesk] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebHelpDesk].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebHelpDesk] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebHelpDesk] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebHelpDesk] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebHelpDesk] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebHelpDesk] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebHelpDesk] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebHelpDesk] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WebHelpDesk] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebHelpDesk] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebHelpDesk] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebHelpDesk] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebHelpDesk] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebHelpDesk] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebHelpDesk] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebHelpDesk] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebHelpDesk] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebHelpDesk] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebHelpDesk] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebHelpDesk] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebHelpDesk] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebHelpDesk] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebHelpDesk] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebHelpDesk] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebHelpDesk] SET  READ_WRITE 
GO

ALTER DATABASE [WebHelpDesk] SET RECOVERY FULL 
GO

ALTER DATABASE [WebHelpDesk] SET  MULTI_USER 
GO

ALTER DATABASE [WebHelpDesk] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebHelpDesk] SET DB_CHAINING OFF 
GO


